// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public final class CombinedProto {
  private CombinedProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateEmployeeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateEmployeeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeByRoleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeByRoleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeBySalaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeBySalaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeByDistrictRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeByDistrictRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeByBranchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeByBranchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeByRoleAndBranchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeByRoleAndBranchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeByDistrictAndBranchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeByDistrictAndBranchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeByMinSalaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeByMinSalaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeBySalaryRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeBySalaryRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeByRoleAndMinSalaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeByRoleAndMinSalaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeByDistrictOrderedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeByDistrictOrderedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeNamesByBranchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeNamesByBranchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeNameRole_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeNameRole_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeNamesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmployeeNamesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConflictResolution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConflictResolution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResolutionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResolutionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Schema.proto\"d\n\010Employee\022\n\n\002id\030\001 \001(\003\022\014" +
      "\n\004name\030\002 \001(\t\022\014\n\004role\030\003 \001(\t\022\016\n\006salary\030\004 \001" +
      "(\001\022\020\n\010district\030\005 \001(\t\022\016\n\006branch\030\006 \001(\t\"/\n\020" +
      "EmployeeResponse\022\033\n\010employee\030\001 \001(\0132\t.Emp" +
      "loyee\"1\n\021EmployeesResponse\022\034\n\temployees\030" +
      "\001 \003(\0132\t.Employee\"e\n\025CreateEmployeeReques" +
      "t\022\014\n\004name\030\001 \001(\t\022\014\n\004role\030\002 \001(\t\022\016\n\006salary\030" +
      "\003 \001(\001\022\020\n\010district\030\004 \001(\t\022\016\n\006branch\030\005 \001(\t\"" +
      "!\n\023EmployeeByIdRequest\022\n\n\002id\030\001 \001(\003\"%\n\025Em" +
      "ployeeByRoleRequest\022\014\n\004role\030\001 \001(\t\")\n\027Emp" +
      "loyeeBySalaryRequest\022\016\n\006salary\030\001 \001(\001\"-\n\031" +
      "EmployeeByDistrictRequest\022\020\n\010district\030\001 " +
      "\001(\t\")\n\027EmployeeByBranchRequest\022\016\n\006branch" +
      "\030\001 \001(\t\">\n\036EmployeeByRoleAndBranchRequest" +
      "\022\014\n\004role\030\001 \001(\t\022\016\n\006branch\030\002 \001(\t\"F\n\"Employ" +
      "eeByDistrictAndBranchRequest\022\020\n\010district" +
      "\030\001 \001(\t\022\016\n\006branch\030\002 \001(\t\"/\n\032EmployeeByMinS" +
      "alaryRequest\022\021\n\tminSalary\030\001 \001(\001\"D\n\034Emplo" +
      "yeeBySalaryRangeRequest\022\021\n\tminSalary\030\001 \001" +
      "(\001\022\021\n\tmaxSalary\030\002 \001(\001\"D\n!EmployeeByRoleA" +
      "ndMinSalaryRequest\022\014\n\004role\030\001 \001(\t\022\021\n\tminS" +
      "alary\030\002 \001(\001\"4\n EmployeeByDistrictOrdered" +
      "Request\022\020\n\010district\030\001 \001(\t\".\n\034EmployeeNam" +
      "esByBranchRequest\022\016\n\006branch\030\001 \001(\t\".\n\020Emp" +
      "loyeeNameRole\022\014\n\004name\030\001 \001(\t\022\014\n\004role\030\002 \001(" +
      "\t\"=\n\025EmployeeNamesResponse\022$\n\temployees\030" +
      "\001 \003(\0132\021.EmployeeNameRole\"C\n\tFileChunk\022\021\n" +
      "\tfile_name\030\001 \001(\t\022\017\n\007content\030\002 \001(\014\022\022\n\nses" +
      "sion_id\030\003 \001(\t\"\260\001\n\014UploadStatus\022\026\n\016bytes_" +
      "received\030\001 \001(\003\022\017\n\007success\030\002 \001(\010\022\021\n\tfile_" +
      "name\030\003 \001(\t\022,\n\010conflict\030\004 \001(\0162\032.UploadSta" +
      "tus.ConflictType\"6\n\014ConflictType\022\010\n\004NONE" +
      "\020\000\022\r\n\tIDENTICAL\020\001\022\r\n\tDIFFERENT\020\002\"\325\001\n\022Con" +
      "flictResolution\022\021\n\tfile_name\030\001 \001(\t\0224\n\006ch" +
      "oice\030\002 \001(\0162$.ConflictResolution.Resoluti" +
      "onChoice\022\025\n\rnew_file_name\030\003 \001(\t\022\022\n\nsessi" +
      "on_id\030\004 \001(\t\"K\n\020ResolutionChoice\022\n\n\006CANCE" +
      "L\020\000\022\014\n\010OVERRIDE\020\001\022\n\n\006RENAME\020\002\022\021\n\rKEEP_EX" +
      "ISTING\020\003\"6\n\022ResolutionResponse\022\017\n\007succes" +
      "s\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\" \n\013FileRequest\022" +
      "\021\n\tfile_name\030\001 \001(\t\"9\n\010FileInfo\022\021\n\tfile_n" +
      "ame\030\001 \001(\t\022\014\n\004size\030\002 \001(\003\022\014\n\004hash\030\003 \001(\014\"\007\n" +
      "\005Empty\"\036\n\010FileList\022\022\n\nfile_names\030\001 \003(\t2\300" +
      "\010\n\017EmployeeService\022;\n\016CreateEmployee\022\026.C" +
      "reateEmployeeRequest\032\021.EmployeeResponse\022" +
      ":\n\017GetEmployeeById\022\024.EmployeeByIdRequest" +
      "\032\021.EmployeeResponse\022@\n\022GetEmployeesByRol" +
      "e\022\026.EmployeeByRoleRequest\032\022.EmployeesRes" +
      "ponse\022D\n\024GetEmployeesBySalary\022\030.Employee" +
      "BySalaryRequest\032\022.EmployeesResponse\022H\n\026G" +
      "etEmployeesByDistrict\022\032.EmployeeByDistri" +
      "ctRequest\032\022.EmployeesResponse\022D\n\024GetEmpl" +
      "oyeesByBranch\022\030.EmployeeByBranchRequest\032" +
      "\022.EmployeesResponse\022-\n\017GetAllEmployees\022\006" +
      ".Empty\032\022.EmployeesResponse\022R\n\033GetEmploye" +
      "esByRoleAndBranch\022\037.EmployeeByRoleAndBra" +
      "nchRequest\032\022.EmployeesResponse\022Z\n\037GetEmp" +
      "loyeesByDistrictAndBranch\022#.EmployeeByDi" +
      "strictAndBranchRequest\032\022.EmployeesRespon" +
      "se\022T\n!GetEmployeesWithSalaryGreaterThan\022" +
      "\033.EmployeeByMinSalaryRequest\032\022.Employees" +
      "Response\022R\n\035GetEmployeesWithSalaryBetwee" +
      "n\022\035.EmployeeBySalaryRangeRequest\032\022.Emplo" +
      "yeesResponse\022X\n\036GetEmployeesByRoleAndMin" +
      "Salary\022\".EmployeeByRoleAndMinSalaryReque" +
      "st\032\022.EmployeesResponse\022^\n%GetEmployeesBy" +
      "DistrictOrderedBySalary\022!.EmployeeByDist" +
      "rictOrderedRequest\032\022.EmployeesResponse\022Y" +
      "\n GetEmployeeNamesAndRolesByBranch\022\035.Emp" +
      "loyeeNamesByBranchRequest\032\026.EmployeeName" +
      "sResponse2\375\001\n\023FileTransferService\022-\n\nUpl" +
      "oadFile\022\n.FileChunk\032\r.UploadStatus\"\000(\0010\001" +
      "\022=\n\017ResolveConflict\022\023.ConflictResolution" +
      "\032\023.ResolutionResponse\"\000\022,\n\014DownloadFile\022" +
      "\014.FileRequest\032\n.FileChunk\"\0000\001\022 \n\tListFil" +
      "es\022\006.Empty\032\t.FileList\"\000\022(\n\013GetFileInfo\022\014" +
      ".FileRequest\032\t.FileInfo\"\000B,\n\031com.example" +
      ".combined.grpcB\rCombinedProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", "Role", "Salary", "District", "Branch", });
    internal_static_EmployeeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmployeeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeResponse_descriptor,
        new java.lang.String[] { "Employee", });
    internal_static_EmployeesResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EmployeesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeesResponse_descriptor,
        new java.lang.String[] { "Employees", });
    internal_static_CreateEmployeeRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CreateEmployeeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateEmployeeRequest_descriptor,
        new java.lang.String[] { "Name", "Role", "Salary", "District", "Branch", });
    internal_static_EmployeeByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_EmployeeByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_EmployeeByRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_EmployeeByRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeByRoleRequest_descriptor,
        new java.lang.String[] { "Role", });
    internal_static_EmployeeBySalaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_EmployeeBySalaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeBySalaryRequest_descriptor,
        new java.lang.String[] { "Salary", });
    internal_static_EmployeeByDistrictRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_EmployeeByDistrictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeByDistrictRequest_descriptor,
        new java.lang.String[] { "District", });
    internal_static_EmployeeByBranchRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_EmployeeByBranchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeByBranchRequest_descriptor,
        new java.lang.String[] { "Branch", });
    internal_static_EmployeeByRoleAndBranchRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_EmployeeByRoleAndBranchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeByRoleAndBranchRequest_descriptor,
        new java.lang.String[] { "Role", "Branch", });
    internal_static_EmployeeByDistrictAndBranchRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_EmployeeByDistrictAndBranchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeByDistrictAndBranchRequest_descriptor,
        new java.lang.String[] { "District", "Branch", });
    internal_static_EmployeeByMinSalaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_EmployeeByMinSalaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeByMinSalaryRequest_descriptor,
        new java.lang.String[] { "MinSalary", });
    internal_static_EmployeeBySalaryRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_EmployeeBySalaryRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeBySalaryRangeRequest_descriptor,
        new java.lang.String[] { "MinSalary", "MaxSalary", });
    internal_static_EmployeeByRoleAndMinSalaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_EmployeeByRoleAndMinSalaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeByRoleAndMinSalaryRequest_descriptor,
        new java.lang.String[] { "Role", "MinSalary", });
    internal_static_EmployeeByDistrictOrderedRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_EmployeeByDistrictOrderedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeByDistrictOrderedRequest_descriptor,
        new java.lang.String[] { "District", });
    internal_static_EmployeeNamesByBranchRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_EmployeeNamesByBranchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeNamesByBranchRequest_descriptor,
        new java.lang.String[] { "Branch", });
    internal_static_EmployeeNameRole_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_EmployeeNameRole_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeNameRole_descriptor,
        new java.lang.String[] { "Name", "Role", });
    internal_static_EmployeeNamesResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_EmployeeNamesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmployeeNamesResponse_descriptor,
        new java.lang.String[] { "Employees", });
    internal_static_FileChunk_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_FileChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileChunk_descriptor,
        new java.lang.String[] { "FileName", "Content", "SessionId", });
    internal_static_UploadStatus_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_UploadStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadStatus_descriptor,
        new java.lang.String[] { "BytesReceived", "Success", "FileName", "Conflict", });
    internal_static_ConflictResolution_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_ConflictResolution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConflictResolution_descriptor,
        new java.lang.String[] { "FileName", "Choice", "NewFileName", "SessionId", });
    internal_static_ResolutionResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_ResolutionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResolutionResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_FileRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_FileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileRequest_descriptor,
        new java.lang.String[] { "FileName", });
    internal_static_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileInfo_descriptor,
        new java.lang.String[] { "FileName", "Size", "Hash", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_FileList_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_FileList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileList_descriptor,
        new java.lang.String[] { "FileNames", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
