// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface ConflictResolutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConflictResolution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_name = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>.ConflictResolution.ResolutionChoice choice = 2;</code>
   * @return The enum numeric value on the wire for choice.
   */
  int getChoiceValue();
  /**
   * <code>.ConflictResolution.ResolutionChoice choice = 2;</code>
   * @return The choice.
   */
  com.example.combined.grpc.ConflictResolution.ResolutionChoice getChoice();

  /**
   * <code>string new_file_name = 3;</code>
   * @return The newFileName.
   */
  java.lang.String getNewFileName();
  /**
   * <code>string new_file_name = 3;</code>
   * @return The bytes for newFileName.
   */
  com.google.protobuf.ByteString
      getNewFileNameBytes();

  /**
   * <code>string session_id = 4;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 4;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
