// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface CreateEmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateEmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string role = 2;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 2;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>double salary = 3;</code>
   * @return The salary.
   */
  double getSalary();

  /**
   * <code>string district = 4;</code>
   * @return The district.
   */
  java.lang.String getDistrict();
  /**
   * <code>string district = 4;</code>
   * @return The bytes for district.
   */
  com.google.protobuf.ByteString
      getDistrictBytes();

  /**
   * <code>string branch = 5;</code>
   * @return The branch.
   */
  java.lang.String getBranch();
  /**
   * <code>string branch = 5;</code>
   * @return The bytes for branch.
   */
  com.google.protobuf.ByteString
      getBranchBytes();
}
