// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface EmployeesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  java.util.List<com.example.combined.grpc.Employee> 
      getEmployeesList();
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  com.example.combined.grpc.Employee getEmployees(int index);
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  java.util.List<? extends com.example.combined.grpc.EmployeeOrBuilder> 
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  com.example.combined.grpc.EmployeeOrBuilder getEmployeesOrBuilder(
      int index);
}
