// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface EmployeeByRoleAndBranchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeByRoleAndBranchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string role = 1;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 1;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string branch = 2;</code>
   * @return The branch.
   */
  java.lang.String getBranch();
  /**
   * <code>string branch = 2;</code>
   * @return The bytes for branch.
   */
  com.google.protobuf.ByteString
      getBranchBytes();
}
