// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

/**
 * Protobuf type {@code EmployeeByRoleAndMinSalaryRequest}
 */
public final class EmployeeByRoleAndMinSalaryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EmployeeByRoleAndMinSalaryRequest)
    EmployeeByRoleAndMinSalaryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeByRoleAndMinSalaryRequest.newBuilder() to construct.
  private EmployeeByRoleAndMinSalaryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeByRoleAndMinSalaryRequest() {
    role_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmployeeByRoleAndMinSalaryRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByRoleAndMinSalaryRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByRoleAndMinSalaryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest.class, com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest.Builder.class);
  }

  public static final int ROLE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object role_ = "";
  /**
   * <code>string role = 1;</code>
   * @return The role.
   */
  @java.lang.Override
  public java.lang.String getRole() {
    java.lang.Object ref = role_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      role_ = s;
      return s;
    }
  }
  /**
   * <code>string role = 1;</code>
   * @return The bytes for role.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoleBytes() {
    java.lang.Object ref = role_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      role_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MINSALARY_FIELD_NUMBER = 2;
  private double minSalary_ = 0D;
  /**
   * <code>double minSalary = 2;</code>
   * @return The minSalary.
   */
  @java.lang.Override
  public double getMinSalary() {
    return minSalary_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(role_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, role_);
    }
    if (java.lang.Double.doubleToRawLongBits(minSalary_) != 0) {
      output.writeDouble(2, minSalary_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(role_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, role_);
    }
    if (java.lang.Double.doubleToRawLongBits(minSalary_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, minSalary_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest)) {
      return super.equals(obj);
    }
    com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest other = (com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest) obj;

    if (!getRole()
        .equals(other.getRole())) return false;
    if (java.lang.Double.doubleToLongBits(getMinSalary())
        != java.lang.Double.doubleToLongBits(
            other.getMinSalary())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + getRole().hashCode();
    hash = (37 * hash) + MINSALARY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMinSalary()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EmployeeByRoleAndMinSalaryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EmployeeByRoleAndMinSalaryRequest)
      com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByRoleAndMinSalaryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByRoleAndMinSalaryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest.class, com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest.Builder.class);
    }

    // Construct using com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      role_ = "";
      minSalary_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByRoleAndMinSalaryRequest_descriptor;
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest getDefaultInstanceForType() {
      return com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest build() {
      com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest buildPartial() {
      com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest result = new com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.role_ = role_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.minSalary_ = minSalary_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest) {
        return mergeFrom((com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest other) {
      if (other == com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest.getDefaultInstance()) return this;
      if (!other.getRole().isEmpty()) {
        role_ = other.role_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getMinSalary() != 0D) {
        setMinSalary(other.getMinSalary());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              role_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              minSalary_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object role_ = "";
    /**
     * <code>string role = 1;</code>
     * @return The role.
     */
    public java.lang.String getRole() {
      java.lang.Object ref = role_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        role_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string role = 1;</code>
     * @return The bytes for role.
     */
    public com.google.protobuf.ByteString
        getRoleBytes() {
      java.lang.Object ref = role_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        role_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string role = 1;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      role_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string role = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      role_ = getDefaultInstance().getRole();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string role = 1;</code>
     * @param value The bytes for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      role_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double minSalary_ ;
    /**
     * <code>double minSalary = 2;</code>
     * @return The minSalary.
     */
    @java.lang.Override
    public double getMinSalary() {
      return minSalary_;
    }
    /**
     * <code>double minSalary = 2;</code>
     * @param value The minSalary to set.
     * @return This builder for chaining.
     */
    public Builder setMinSalary(double value) {

      minSalary_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double minSalary = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinSalary() {
      bitField0_ = (bitField0_ & ~0x00000002);
      minSalary_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EmployeeByRoleAndMinSalaryRequest)
  }

  // @@protoc_insertion_point(class_scope:EmployeeByRoleAndMinSalaryRequest)
  private static final com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest();
  }

  public static com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeByRoleAndMinSalaryRequest>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeByRoleAndMinSalaryRequest>() {
    @java.lang.Override
    public EmployeeByRoleAndMinSalaryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmployeeByRoleAndMinSalaryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeByRoleAndMinSalaryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.combined.grpc.EmployeeByRoleAndMinSalaryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

