// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

/**
 * Protobuf type {@code EmployeeNamesResponse}
 */
public final class EmployeeNamesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EmployeeNamesResponse)
    EmployeeNamesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeNamesResponse.newBuilder() to construct.
  private EmployeeNamesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeNamesResponse() {
    employees_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmployeeNamesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.combined.grpc.CombinedProto.internal_static_EmployeeNamesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.combined.grpc.CombinedProto.internal_static_EmployeeNamesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.combined.grpc.EmployeeNamesResponse.class, com.example.combined.grpc.EmployeeNamesResponse.Builder.class);
  }

  public static final int EMPLOYEES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.example.combined.grpc.EmployeeNameRole> employees_;
  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.combined.grpc.EmployeeNameRole> getEmployeesList() {
    return employees_;
  }
  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.combined.grpc.EmployeeNameRoleOrBuilder> 
      getEmployeesOrBuilderList() {
    return employees_;
  }
  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  @java.lang.Override
  public int getEmployeesCount() {
    return employees_.size();
  }
  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  @java.lang.Override
  public com.example.combined.grpc.EmployeeNameRole getEmployees(int index) {
    return employees_.get(index);
  }
  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  @java.lang.Override
  public com.example.combined.grpc.EmployeeNameRoleOrBuilder getEmployeesOrBuilder(
      int index) {
    return employees_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < employees_.size(); i++) {
      output.writeMessage(1, employees_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < employees_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, employees_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.combined.grpc.EmployeeNamesResponse)) {
      return super.equals(obj);
    }
    com.example.combined.grpc.EmployeeNamesResponse other = (com.example.combined.grpc.EmployeeNamesResponse) obj;

    if (!getEmployeesList()
        .equals(other.getEmployeesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEmployeesCount() > 0) {
      hash = (37 * hash) + EMPLOYEES_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.combined.grpc.EmployeeNamesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.combined.grpc.EmployeeNamesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.combined.grpc.EmployeeNamesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.combined.grpc.EmployeeNamesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EmployeeNamesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EmployeeNamesResponse)
      com.example.combined.grpc.EmployeeNamesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeNamesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeNamesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.combined.grpc.EmployeeNamesResponse.class, com.example.combined.grpc.EmployeeNamesResponse.Builder.class);
    }

    // Construct using com.example.combined.grpc.EmployeeNamesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (employeesBuilder_ == null) {
        employees_ = java.util.Collections.emptyList();
      } else {
        employees_ = null;
        employeesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeNamesResponse_descriptor;
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeNamesResponse getDefaultInstanceForType() {
      return com.example.combined.grpc.EmployeeNamesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeNamesResponse build() {
      com.example.combined.grpc.EmployeeNamesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeNamesResponse buildPartial() {
      com.example.combined.grpc.EmployeeNamesResponse result = new com.example.combined.grpc.EmployeeNamesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.combined.grpc.EmployeeNamesResponse result) {
      if (employeesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          employees_ = java.util.Collections.unmodifiableList(employees_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.employees_ = employees_;
      } else {
        result.employees_ = employeesBuilder_.build();
      }
    }

    private void buildPartial0(com.example.combined.grpc.EmployeeNamesResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.combined.grpc.EmployeeNamesResponse) {
        return mergeFrom((com.example.combined.grpc.EmployeeNamesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.combined.grpc.EmployeeNamesResponse other) {
      if (other == com.example.combined.grpc.EmployeeNamesResponse.getDefaultInstance()) return this;
      if (employeesBuilder_ == null) {
        if (!other.employees_.isEmpty()) {
          if (employees_.isEmpty()) {
            employees_ = other.employees_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmployeesIsMutable();
            employees_.addAll(other.employees_);
          }
          onChanged();
        }
      } else {
        if (!other.employees_.isEmpty()) {
          if (employeesBuilder_.isEmpty()) {
            employeesBuilder_.dispose();
            employeesBuilder_ = null;
            employees_ = other.employees_;
            bitField0_ = (bitField0_ & ~0x00000001);
            employeesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmployeesFieldBuilder() : null;
          } else {
            employeesBuilder_.addAllMessages(other.employees_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.combined.grpc.EmployeeNameRole m =
                  input.readMessage(
                      com.example.combined.grpc.EmployeeNameRole.parser(),
                      extensionRegistry);
              if (employeesBuilder_ == null) {
                ensureEmployeesIsMutable();
                employees_.add(m);
              } else {
                employeesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.combined.grpc.EmployeeNameRole> employees_ =
      java.util.Collections.emptyList();
    private void ensureEmployeesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        employees_ = new java.util.ArrayList<com.example.combined.grpc.EmployeeNameRole>(employees_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.combined.grpc.EmployeeNameRole, com.example.combined.grpc.EmployeeNameRole.Builder, com.example.combined.grpc.EmployeeNameRoleOrBuilder> employeesBuilder_;

    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public java.util.List<com.example.combined.grpc.EmployeeNameRole> getEmployeesList() {
      if (employeesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(employees_);
      } else {
        return employeesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public int getEmployeesCount() {
      if (employeesBuilder_ == null) {
        return employees_.size();
      } else {
        return employeesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public com.example.combined.grpc.EmployeeNameRole getEmployees(int index) {
      if (employeesBuilder_ == null) {
        return employees_.get(index);
      } else {
        return employeesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public Builder setEmployees(
        int index, com.example.combined.grpc.EmployeeNameRole value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.set(index, value);
        onChanged();
      } else {
        employeesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public Builder setEmployees(
        int index, com.example.combined.grpc.EmployeeNameRole.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.set(index, builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public Builder addEmployees(com.example.combined.grpc.EmployeeNameRole value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.add(value);
        onChanged();
      } else {
        employeesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public Builder addEmployees(
        int index, com.example.combined.grpc.EmployeeNameRole value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.add(index, value);
        onChanged();
      } else {
        employeesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public Builder addEmployees(
        com.example.combined.grpc.EmployeeNameRole.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.add(builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public Builder addEmployees(
        int index, com.example.combined.grpc.EmployeeNameRole.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.add(index, builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public Builder addAllEmployees(
        java.lang.Iterable<? extends com.example.combined.grpc.EmployeeNameRole> values) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, employees_);
        onChanged();
      } else {
        employeesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public Builder clearEmployees() {
      if (employeesBuilder_ == null) {
        employees_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        employeesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public Builder removeEmployees(int index) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.remove(index);
        onChanged();
      } else {
        employeesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public com.example.combined.grpc.EmployeeNameRole.Builder getEmployeesBuilder(
        int index) {
      return getEmployeesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public com.example.combined.grpc.EmployeeNameRoleOrBuilder getEmployeesOrBuilder(
        int index) {
      if (employeesBuilder_ == null) {
        return employees_.get(index);  } else {
        return employeesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public java.util.List<? extends com.example.combined.grpc.EmployeeNameRoleOrBuilder> 
         getEmployeesOrBuilderList() {
      if (employeesBuilder_ != null) {
        return employeesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(employees_);
      }
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public com.example.combined.grpc.EmployeeNameRole.Builder addEmployeesBuilder() {
      return getEmployeesFieldBuilder().addBuilder(
          com.example.combined.grpc.EmployeeNameRole.getDefaultInstance());
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public com.example.combined.grpc.EmployeeNameRole.Builder addEmployeesBuilder(
        int index) {
      return getEmployeesFieldBuilder().addBuilder(
          index, com.example.combined.grpc.EmployeeNameRole.getDefaultInstance());
    }
    /**
     * <code>repeated .EmployeeNameRole employees = 1;</code>
     */
    public java.util.List<com.example.combined.grpc.EmployeeNameRole.Builder> 
         getEmployeesBuilderList() {
      return getEmployeesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.combined.grpc.EmployeeNameRole, com.example.combined.grpc.EmployeeNameRole.Builder, com.example.combined.grpc.EmployeeNameRoleOrBuilder> 
        getEmployeesFieldBuilder() {
      if (employeesBuilder_ == null) {
        employeesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.combined.grpc.EmployeeNameRole, com.example.combined.grpc.EmployeeNameRole.Builder, com.example.combined.grpc.EmployeeNameRoleOrBuilder>(
                employees_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        employees_ = null;
      }
      return employeesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EmployeeNamesResponse)
  }

  // @@protoc_insertion_point(class_scope:EmployeeNamesResponse)
  private static final com.example.combined.grpc.EmployeeNamesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.combined.grpc.EmployeeNamesResponse();
  }

  public static com.example.combined.grpc.EmployeeNamesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeNamesResponse>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeNamesResponse>() {
    @java.lang.Override
    public EmployeeNamesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmployeeNamesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeNamesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.combined.grpc.EmployeeNamesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

