// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface EmployeeNamesByBranchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeNamesByBranchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string branch = 1;</code>
   * @return The branch.
   */
  java.lang.String getBranch();
  /**
   * <code>string branch = 1;</code>
   * @return The bytes for branch.
   */
  com.google.protobuf.ByteString
      getBranchBytes();
}
