// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface EmployeeBySalaryRangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeBySalaryRangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double minSalary = 1;</code>
   * @return The minSalary.
   */
  double getMinSalary();

  /**
   * <code>double maxSalary = 2;</code>
   * @return The maxSalary.
   */
  double getMaxSalary();
}
