// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface EmployeeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Employee employee = 1;</code>
   * @return Whether the employee field is set.
   */
  boolean hasEmployee();
  /**
   * <code>.Employee employee = 1;</code>
   * @return The employee.
   */
  com.example.combined.grpc.Employee getEmployee();
  /**
   * <code>.Employee employee = 1;</code>
   */
  com.example.combined.grpc.EmployeeOrBuilder getEmployeeOrBuilder();
}
