// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface EmployeeByRoleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeByRoleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string role = 1;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 1;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
