// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface EmployeeNamesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeNamesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  java.util.List<com.example.combined.grpc.EmployeeNameRole> 
      getEmployeesList();
  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  com.example.combined.grpc.EmployeeNameRole getEmployees(int index);
  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  java.util.List<? extends com.example.combined.grpc.EmployeeNameRoleOrBuilder> 
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .EmployeeNameRole employees = 1;</code>
   */
  com.example.combined.grpc.EmployeeNameRoleOrBuilder getEmployeesOrBuilder(
      int index);
}
