// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

/**
 * Protobuf type {@code EmployeeResponse}
 */
public final class EmployeeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EmployeeResponse)
    EmployeeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeResponse.newBuilder() to construct.
  private EmployeeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmployeeResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.combined.grpc.CombinedProto.internal_static_EmployeeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.combined.grpc.CombinedProto.internal_static_EmployeeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.combined.grpc.EmployeeResponse.class, com.example.combined.grpc.EmployeeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int EMPLOYEE_FIELD_NUMBER = 1;
  private com.example.combined.grpc.Employee employee_;
  /**
   * <code>.Employee employee = 1;</code>
   * @return Whether the employee field is set.
   */
  @java.lang.Override
  public boolean hasEmployee() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Employee employee = 1;</code>
   * @return The employee.
   */
  @java.lang.Override
  public com.example.combined.grpc.Employee getEmployee() {
    return employee_ == null ? com.example.combined.grpc.Employee.getDefaultInstance() : employee_;
  }
  /**
   * <code>.Employee employee = 1;</code>
   */
  @java.lang.Override
  public com.example.combined.grpc.EmployeeOrBuilder getEmployeeOrBuilder() {
    return employee_ == null ? com.example.combined.grpc.Employee.getDefaultInstance() : employee_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getEmployee());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEmployee());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.combined.grpc.EmployeeResponse)) {
      return super.equals(obj);
    }
    com.example.combined.grpc.EmployeeResponse other = (com.example.combined.grpc.EmployeeResponse) obj;

    if (hasEmployee() != other.hasEmployee()) return false;
    if (hasEmployee()) {
      if (!getEmployee()
          .equals(other.getEmployee())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEmployee()) {
      hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
      hash = (53 * hash) + getEmployee().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.combined.grpc.EmployeeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.combined.grpc.EmployeeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.combined.grpc.EmployeeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.combined.grpc.EmployeeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.combined.grpc.EmployeeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.combined.grpc.EmployeeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EmployeeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EmployeeResponse)
      com.example.combined.grpc.EmployeeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.combined.grpc.EmployeeResponse.class, com.example.combined.grpc.EmployeeResponse.Builder.class);
    }

    // Construct using com.example.combined.grpc.EmployeeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmployeeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      employee_ = null;
      if (employeeBuilder_ != null) {
        employeeBuilder_.dispose();
        employeeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeResponse_descriptor;
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeResponse getDefaultInstanceForType() {
      return com.example.combined.grpc.EmployeeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeResponse build() {
      com.example.combined.grpc.EmployeeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeResponse buildPartial() {
      com.example.combined.grpc.EmployeeResponse result = new com.example.combined.grpc.EmployeeResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.combined.grpc.EmployeeResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.employee_ = employeeBuilder_ == null
            ? employee_
            : employeeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.combined.grpc.EmployeeResponse) {
        return mergeFrom((com.example.combined.grpc.EmployeeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.combined.grpc.EmployeeResponse other) {
      if (other == com.example.combined.grpc.EmployeeResponse.getDefaultInstance()) return this;
      if (other.hasEmployee()) {
        mergeEmployee(other.getEmployee());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getEmployeeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.example.combined.grpc.Employee employee_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.combined.grpc.Employee, com.example.combined.grpc.Employee.Builder, com.example.combined.grpc.EmployeeOrBuilder> employeeBuilder_;
    /**
     * <code>.Employee employee = 1;</code>
     * @return Whether the employee field is set.
     */
    public boolean hasEmployee() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Employee employee = 1;</code>
     * @return The employee.
     */
    public com.example.combined.grpc.Employee getEmployee() {
      if (employeeBuilder_ == null) {
        return employee_ == null ? com.example.combined.grpc.Employee.getDefaultInstance() : employee_;
      } else {
        return employeeBuilder_.getMessage();
      }
    }
    /**
     * <code>.Employee employee = 1;</code>
     */
    public Builder setEmployee(com.example.combined.grpc.Employee value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        employee_ = value;
      } else {
        employeeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Employee employee = 1;</code>
     */
    public Builder setEmployee(
        com.example.combined.grpc.Employee.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        employee_ = builderForValue.build();
      } else {
        employeeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Employee employee = 1;</code>
     */
    public Builder mergeEmployee(com.example.combined.grpc.Employee value) {
      if (employeeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          employee_ != null &&
          employee_ != com.example.combined.grpc.Employee.getDefaultInstance()) {
          getEmployeeBuilder().mergeFrom(value);
        } else {
          employee_ = value;
        }
      } else {
        employeeBuilder_.mergeFrom(value);
      }
      if (employee_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Employee employee = 1;</code>
     */
    public Builder clearEmployee() {
      bitField0_ = (bitField0_ & ~0x00000001);
      employee_ = null;
      if (employeeBuilder_ != null) {
        employeeBuilder_.dispose();
        employeeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Employee employee = 1;</code>
     */
    public com.example.combined.grpc.Employee.Builder getEmployeeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getEmployeeFieldBuilder().getBuilder();
    }
    /**
     * <code>.Employee employee = 1;</code>
     */
    public com.example.combined.grpc.EmployeeOrBuilder getEmployeeOrBuilder() {
      if (employeeBuilder_ != null) {
        return employeeBuilder_.getMessageOrBuilder();
      } else {
        return employee_ == null ?
            com.example.combined.grpc.Employee.getDefaultInstance() : employee_;
      }
    }
    /**
     * <code>.Employee employee = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.combined.grpc.Employee, com.example.combined.grpc.Employee.Builder, com.example.combined.grpc.EmployeeOrBuilder> 
        getEmployeeFieldBuilder() {
      if (employeeBuilder_ == null) {
        employeeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.combined.grpc.Employee, com.example.combined.grpc.Employee.Builder, com.example.combined.grpc.EmployeeOrBuilder>(
                getEmployee(),
                getParentForChildren(),
                isClean());
        employee_ = null;
      }
      return employeeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EmployeeResponse)
  }

  // @@protoc_insertion_point(class_scope:EmployeeResponse)
  private static final com.example.combined.grpc.EmployeeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.combined.grpc.EmployeeResponse();
  }

  public static com.example.combined.grpc.EmployeeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeResponse>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeResponse>() {
    @java.lang.Override
    public EmployeeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmployeeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.combined.grpc.EmployeeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

