// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface EmployeeByDistrictRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeByDistrictRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string district = 1;</code>
   * @return The district.
   */
  java.lang.String getDistrict();
  /**
   * <code>string district = 1;</code>
   * @return The bytes for district.
   */
  com.google.protobuf.ByteString
      getDistrictBytes();
}
