// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface EmployeeBySalaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeBySalaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double salary = 1;</code>
   * @return The salary.
   */
  double getSalary();
}
