// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

/**
 * Protobuf type {@code EmployeeByDistrictOrderedRequest}
 */
public final class EmployeeByDistrictOrderedRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EmployeeByDistrictOrderedRequest)
    EmployeeByDistrictOrderedRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeByDistrictOrderedRequest.newBuilder() to construct.
  private EmployeeByDistrictOrderedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeByDistrictOrderedRequest() {
    district_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmployeeByDistrictOrderedRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByDistrictOrderedRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByDistrictOrderedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.combined.grpc.EmployeeByDistrictOrderedRequest.class, com.example.combined.grpc.EmployeeByDistrictOrderedRequest.Builder.class);
  }

  public static final int DISTRICT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object district_ = "";
  /**
   * <code>string district = 1;</code>
   * @return The district.
   */
  @java.lang.Override
  public java.lang.String getDistrict() {
    java.lang.Object ref = district_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      district_ = s;
      return s;
    }
  }
  /**
   * <code>string district = 1;</code>
   * @return The bytes for district.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDistrictBytes() {
    java.lang.Object ref = district_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      district_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(district_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, district_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(district_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, district_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.combined.grpc.EmployeeByDistrictOrderedRequest)) {
      return super.equals(obj);
    }
    com.example.combined.grpc.EmployeeByDistrictOrderedRequest other = (com.example.combined.grpc.EmployeeByDistrictOrderedRequest) obj;

    if (!getDistrict()
        .equals(other.getDistrict())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISTRICT_FIELD_NUMBER;
    hash = (53 * hash) + getDistrict().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.combined.grpc.EmployeeByDistrictOrderedRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EmployeeByDistrictOrderedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EmployeeByDistrictOrderedRequest)
      com.example.combined.grpc.EmployeeByDistrictOrderedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByDistrictOrderedRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByDistrictOrderedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.combined.grpc.EmployeeByDistrictOrderedRequest.class, com.example.combined.grpc.EmployeeByDistrictOrderedRequest.Builder.class);
    }

    // Construct using com.example.combined.grpc.EmployeeByDistrictOrderedRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      district_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.combined.grpc.CombinedProto.internal_static_EmployeeByDistrictOrderedRequest_descriptor;
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeByDistrictOrderedRequest getDefaultInstanceForType() {
      return com.example.combined.grpc.EmployeeByDistrictOrderedRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeByDistrictOrderedRequest build() {
      com.example.combined.grpc.EmployeeByDistrictOrderedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.combined.grpc.EmployeeByDistrictOrderedRequest buildPartial() {
      com.example.combined.grpc.EmployeeByDistrictOrderedRequest result = new com.example.combined.grpc.EmployeeByDistrictOrderedRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.combined.grpc.EmployeeByDistrictOrderedRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.district_ = district_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.combined.grpc.EmployeeByDistrictOrderedRequest) {
        return mergeFrom((com.example.combined.grpc.EmployeeByDistrictOrderedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.combined.grpc.EmployeeByDistrictOrderedRequest other) {
      if (other == com.example.combined.grpc.EmployeeByDistrictOrderedRequest.getDefaultInstance()) return this;
      if (!other.getDistrict().isEmpty()) {
        district_ = other.district_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              district_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object district_ = "";
    /**
     * <code>string district = 1;</code>
     * @return The district.
     */
    public java.lang.String getDistrict() {
      java.lang.Object ref = district_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        district_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string district = 1;</code>
     * @return The bytes for district.
     */
    public com.google.protobuf.ByteString
        getDistrictBytes() {
      java.lang.Object ref = district_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        district_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string district = 1;</code>
     * @param value The district to set.
     * @return This builder for chaining.
     */
    public Builder setDistrict(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      district_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string district = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistrict() {
      district_ = getDefaultInstance().getDistrict();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string district = 1;</code>
     * @param value The bytes for district to set.
     * @return This builder for chaining.
     */
    public Builder setDistrictBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      district_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EmployeeByDistrictOrderedRequest)
  }

  // @@protoc_insertion_point(class_scope:EmployeeByDistrictOrderedRequest)
  private static final com.example.combined.grpc.EmployeeByDistrictOrderedRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.combined.grpc.EmployeeByDistrictOrderedRequest();
  }

  public static com.example.combined.grpc.EmployeeByDistrictOrderedRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeByDistrictOrderedRequest>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeByDistrictOrderedRequest>() {
    @java.lang.Override
    public EmployeeByDistrictOrderedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmployeeByDistrictOrderedRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeByDistrictOrderedRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.combined.grpc.EmployeeByDistrictOrderedRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

