// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface FileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_name = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>int64 size = 2;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>bytes hash = 3;</code>
   * @return The hash.
   */
  com.google.protobuf.ByteString getHash();
}
