// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface FileListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string file_names = 1;</code>
   * @return A list containing the fileNames.
   */
  java.util.List<java.lang.String>
      getFileNamesList();
  /**
   * <code>repeated string file_names = 1;</code>
   * @return The count of fileNames.
   */
  int getFileNamesCount();
  /**
   * <code>repeated string file_names = 1;</code>
   * @param index The index of the element to return.
   * @return The fileNames at the given index.
   */
  java.lang.String getFileNames(int index);
  /**
   * <code>repeated string file_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fileNames at the given index.
   */
  com.google.protobuf.ByteString
      getFileNamesBytes(int index);
}
