// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

// Protobuf Java Version: 3.25.6
package com.example.combined.grpc;

public interface UploadStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UploadStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 bytes_received = 1;</code>
   * @return The bytesReceived.
   */
  long getBytesReceived();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string file_name = 3;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 3;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>.UploadStatus.ConflictType conflict = 4;</code>
   * @return The enum numeric value on the wire for conflict.
   */
  int getConflictValue();
  /**
   * <code>.UploadStatus.ConflictType conflict = 4;</code>
   * @return The conflict.
   */
  com.example.combined.grpc.UploadStatus.ConflictType getConflict();
}
